### ISSUE TITLE
Team Call #9 - Jan 16 2021 @ 1000 EST

### ISSUE THREAD

**Issue by gpthio** [siads591-fa20-001-affordable-housing/go_blue#10]
**Summary**

- DB fully prepped with original APN numbers imported
- Spend the next week working on Plotly and Dash and uploading EDA notebooks to GitHub
- Discussed possible extensions of project to Milestone 2, Capstone and/or ex-MADS
- Meet with faculty on Mon Jan 23 to confirm project scope and deliverables are appropriate (TBC)
- Next meeting set for Sat Jan 16 @ 1000 EST

**Tasks**

- [ ] ALL: Work on Plotly and learn how to use shapefiles
- [ ] ALL: Upload EDA notebooks to GitHub `src` folder
- [ ] ALL: Inspect DB for any mismatches
- [ ] ALL: Keep track of all data sources for final report 
- [ ] GT: Work on Dash to add interactivity to visualizations 
- [ ] GT: Top-up Rentometer credits and get remaining rental estimates
- [ ] GT: Book call with Elle, Chris, Anthony

** Notes **

- Will need Dash for interactivity
- If any mismatches in the 10 DB files, should show up as null values. In theory should be OK, but we should check (read into a dataframe) 
- Should upload EDA and experimental files into GitHub, can create branches once we get up to speed on Plotly and Dash
- Can discuss on faculty call the feasibility of extensions or spin-offs of this project for Milestone 2 and/or Capstone. 
- Can also look into collaborating on related projects ex-MADS (e.g. ML to predict sites that will be developed)
- AF heard of a guy who got rich using a model for predictive property redevelopment. Can look into predicting price appreciation and re-zoning.
- Building permits are available online and we could match these with TaxFile
- To extend the project we need a better grip on what is and is not an apartment building as current filtered list includes non-apartment types (e.g. seniors living). ve model for redevelopment
- Or figure out which neighbourhoods are going to appreciate ... it’s out there ... so there are projects out 
- Reviewed MADS curriculum: AF, GT planing to take Milestone 2 in Apr, HKL will take next term (Spring/Summer) as lacking few prerequisites
- New MADS curriculum doc was posted to Orientation course on Coursera on Jan 5
- Have to choose two elective courses
