### ISSUE TITLE
Team Call #10 - Jan 23 2021 @ 1000 EST

### ISSUE THREAD

**Issue by gpthio** [siads591-fa20-001-affordable-housing/go_blue#11]
**Summary**

- Records converted to Kent County from Core Logic (outdated) so all files now link to same ID field
- All data consolidation to be done on DB after `Property Level.csv` completed and uploaded
- Record Block Group of each property to allow filtering at this level - e.g. heat map based on percentage of properties in each block with overall MSHDA score > 15)
- Allow user to specify proximity band for binary MSHDA affordability score (i.e. 0 or 5) - e.g. 5 points if rent estimate is within x% of affordability threshold, 0 otherwise) 
- Proposed hover attributes: Address, SEV, MSHDA overall score, APN (PNUM)
- Switch from shapefiles to GeoJSON to facilitate easier and error-free DB integration 
- Highest level map view attributes: (1) Acreage - slider(2) Overall MSHDA score - vertical color bar (3) SEV - slider
- Slidedocs format to be used for final report
- Catch-up call scheduled on Jan 24 @ 1000 EST
- Pre-call for faculty check-In meeting scheduled on Jan 25 @ 1800 ET

**Tasks**

- [ ] AF/HKL: Prepare code for writing to GeoJSON, KL will modify for writing to PostGIS including flag for writing to textfile or DB
- [ ] AF: Delete shape files on Google Drive and replace with GeoJSON
- [ ] AF: Add column for Walk Score to `Property Level.csv`
- [ ] GT: Start working on UI design for Plotly/Dash
- [ ] GT: Add columns for affordability (0/1), affordability threshold ($) and rent estimate ($) to `Property Level.csv`
- [ ] GT: Resolve GitHub problems pushing to remote from AF local
- [ ] HKL: Prepare Slidedoc outline and save to Google Drive  ALL: Upload EDA notebooks to GitHub src folder
- [ ] HKL: Upload `Property Level.csv` to DB once AF and GT have added new columns
- [ ] ALL: Learn how to preserve zoom setting and lat/lng of last map view to prevent map resetting view to highest level when filters are selected (KL posted possible solution in Slack). Other problem is time to refresh view.
- [ ] ALL: Reduce opacity of parcel outline to reveal individual properties underneath

**Notes**

- Easy to work directly in DB now that joins have been learned so can push code directly once routines in place
- For Block Groups may want to filter on percentage of properties above a score threshold as averages can be distorted by outliers
- Overall MSHDA scores currently ranging 3-16 points so this range will likely increase after adding Walk Score (WS) and affordability so reasonable score threshold from developer POV might be 15 points
- For affordability, take lat/lng of properties with affordability == 1  then apply 1/4 mile radius (after converting to CRS) then run list of properties from `universe` to find matches which receive 5 points, 0 otherwise. 
- User specified proximity band for affordability will expand matched set to include those properties where the estimated rent is within -x% of the affordability level (i.e. $1,264 in KC). For example, with x=10%, an otherwise 0 scored "not expensive enough" property with a Rentometer max_rent estimate between $1,137 (0.9 x $1,264) and $1,264 will still receive 5 points
- At highest level map view, everything looks gray due to all boundaries drawn in black, so if we can control zoom parameter then we could toggle this on/off 
￼- Should increase transparency (alpha) of parcel outlines (yellow) to see individual properties (
- Need to start looking at designing the UI around the plot. Can use html editor in JetBrains. DCC controls html objects. 
Callback ignores html and just plots the graph.
￼- KL encountered problems running and modifying AF's code as it crashed while searching for shapefiles. AF has uploaded all necessary shapefiles to Google Drive and these will never change. But still have issues using datafiles in geopandas as it seems to require additional shapefiles.  So when we push only one of the shapefiles to the DB, when we make use of the data will we get an error. Alternative is not push to DB, just load through a geopandas read ...
- We can skip SHP and just use GeoJSON which is easier for working with DB. Just export to GeoJSON using a single file. Reference: [Writing Spatial Data](https://geopandas.org/io.html#writing-spatial-data)
