### ISSUE TITLE
Team Call #2 - Nov 28 2020 @ 1800 EST

### ISSUE THREAD

**Issue by gpthio** [siads591-fa20-001-affordable-housing/go_blue#2]
**Summary**
- Reviewed shared project documents and scoring criteria
- Created project timeline and assigned task responsibilities 
- Continued iterating project proposal 
- Next call scheduled for Dec 3 @ 0930 EST

**Tasks**
- [ ] Try to get free/discounted access to ATTOM and UM databases - AF
- [ ] Explore use of Google Maps - HKL
- [ ] Explore market rental databases such - GT 
- [ ] Set up project GitHub repository - GT

**Scoring Criteria**
- Employment Opportunities: HKL suggested we use broader economic measures such as identifying commercial and industrial activities from which jobs will naturally follow
- Zoning: This is lot specific and is often changed such as for vacant parcels. Rezoning is indeed a major feature for redevelopment projects
- Proximity: Need to know what is nearby - e.g.  Alan located a potential project on a gov’t owned site but it was only a mile away from an industrial site which made it unsuitable for housing. Indeed, projects can get vetoed for these reasons. We may want to remove proximity to city center as a criteria. 
- Historic: This is a designation by the state of MI which gives extra points
- State points system (see below) exists in order to qualify for gov't grants which make the projects viable for developers. First 7 criteria in our list determine the score:

1. Proximity to Transportation - e.g. Bus stops
2. Proximity to Amenities - e.g. Grocery Store
3. Proximity to Amenities - e.g. Pharmacy
4. Proximity to Amenities - e.g. School
5. Proximity to Amenities - e.g,. Park
6. Proximity to Amenities - Senior Center
7. Education, Health and Well-Being, etc.

**Other Factors**
- Vacancies: HKL noted that data could be misleading given for example a high proportion of short-term rental properties such as Airbnb -- i.e.  Just because a property is vacant, doesn’t mean it is neglected or meant to be rented out. Keep for now and investigate further.
- Affordability: Formula for affordable monthly rent is Annual Median Income  x 30% / 12  x 40-60. But affordability is not sole consideration. As noted above, a project located in or near an industrial sites is unlikely to get approved. The ability to meet demand and rent out all the units is a prime consideration. Alan mentioned a property in Lansing that is currently at 20% vacancy rate. Have to perform a thorough market study to determine the current demand and if the market can support the proposed rental rate. HKL noted that returns for affordable housing are asymmetric with limitless downside, but upside capped by rent rate limitations imposed in return for gov't grants
- Lot Size: There are many lots. Alan mentioned that in Grand Rapids for anything under 1 acre, you lose 95%. Needle in a haystack problem.
- How does the grant system work?  You self-score your project then submit to state. State budget is split among a few categories. For each project, it will verify scoring and fund based on scoring until the budget is depleted. Absolute caps exist on how much funding each project can apply for. Process is mechanical/formulaic unless the project is deemed to be “strategic” and critical to the community.
- Seniors: Should retain this criteria as it can be filtered out as necessary. Can get it from ATTOM but maybe we should use Google Maps API?
- ATTOM vs Google Maps: Would have to get a list of schools, senior centers, maybe filter by county ... we will have to cross check records -- eg. is our property within 1 mile of school records

**Project Documents**
[591 Supporting Information for Appendices](https://docs.google.com/spreadsheets/d/1SQcRcvS3eKRzv1LDXZmfYcvn6L-gbvRa/edit#gid=1844231050)
[591 Project Proposal](https://docs.google.com/document/d/1L3cNuCI0LlPvc5kIgbsPC3jIBiCUC85s_5onEdgI3gA/edit)
[591 Project Timeline](https://docs.google.com/presentation/d/10z2mzx3cE_NMU8URkXxUohwPNuCWUdFZpKPS9xpPyoY/edit)
