### ISSUE TITLE
Team Call #3 - Dec 3 2020 @ 2130 EST

### ISSUE THREAD

**Issue by gpthio** [siads591-fa20-001-affordable-housing/go_blue#3]
**Summary**
- Delved into details of different data sources
- We will explore Tableau based on recommendation by Chris Teplovs (free accounts through UM)
- Continued iterating project proposal for Dec 9 submission deadline
- Next call scheduled for Dec 8 @ 0930 EST

**Tasks**

- [ ] Explore data sources for crime and unemployment - HKL
- [ ] Explore data sources for rental rates - GT
- [ ] Get access to ATTOM and UM databases - AF
- [ ] Explore Tableau - ALL

**Notes**
- Clarified there is no Coursera submission due today other than the Proposal and Project Team Tracker FA2020/WN2021 sheet which has already been updated by HKL. But be sure to individually click Submit button on Coursera. 
- Subject properties will come from ATTOM or UM database
- Rental rates will be used for proximity-cost checks
- If we can get lat/lon then we can compare. Obtaining data from ATTOM and UM is the key.
- Google Maps API will return lat/lon of an address
- For some info, we may not need to toggle between addresses and lat/lon since we are using visual representations. For example, say we are checking crime but can only get this information down to the country level. This is fine as this represents the true nature of the variable and we don’t have to encode down to the specific lat/lon of the property. 
- Use Google Maps to find address, geolocation, then use Google Places to confirm the type of location - e.g. barber, grocery, school
- Google provides $200 worth of credits for all APIs, but this may be insufficient if if cost is determined by total data pulled vs the number of API calls made
- After Dec 9 project proposal submission, next project deadline is Dec 16 to Pull, Verify and Clean Data
- Primary objective between now and Dec 16 is to jointly work on finalizing our data sources
- Everyone to individually explore Tableau

**Documents**
[Proposal and Project Team Tracker FA2020/WN2021](https://docs.google.com/spreadsheets/d/11ZYsDewwvouFrvLj_HwnfkZ2F9TeRHtgmONQAPszfh8/edit#gid=1064547803)
