### ISSUE TITLE
Team Call #4 - Dec 19 2020 @ 1900 EST

### ISSUE THREAD

**Issue by gpthio** [siads591-fa20-001-affordable-housing/go_blue#5]
**Summary**
- AF and GT reviewed and approved changes to revised project proposal after selectively incorporating peer feedback as some of the comments did not warrant any action and/or did not seem useful/sensible (e.g. attaching a size estimate to each data source)
- GT to submit revised proposal pending HKL approval
- Decided to focus on US Census _Block Groups_ for Walk Scores (WS) given 5M+ data points and ability to access only 5K WS records per day
- Assessed project progress and believe all data gathering tasks can be completed by end of next week (Dec 26) after which we can begin data cleansing

**Tasks**

- [ ] HKL: Review and approve revised project proposal for submission
- [ ] ALL: Aim to complete all data gathering responsibilities (Appendix A) by end of next week (Dec 26)
- [ ] ALL: Post data gathering, will divide and conquer data cleansing tasks
- [ ] AF:  Get _shape_ files from US Census Bureau for cross-referencing in Jupyter using _geopandas_ to assist in data cleansing
- [ ] GT: Determine which combination of data sources to use to identify multi-family buildings and their corresponding rental values as there are no one-stop API shops for this. 
- [ ] AF, HKL: Check repo access/visibility which should be fine after GT's account was un-flagged by Github on Dec 8. May need to logout and login to refresh.
- [ ] ALL: Propose next team call on Dec 26 @ 1830 EST

**Notes**
- Most of MI will have a zero WS as there are only a few cities, but get wide WS variation once you are within a city -e.g. scores can range from 70-90 within just a few blocks
- Coding by _Block Groups_ should be manageable and can use the centroid to determine the WS
- Reviewed MSHDA criteria to filter more precisely: (1) Apartment building must have a minimum of 20 units (2) Rents must be at least 40% above the affordability threshold for each apartment size (i.e. 1/2/3 BRs) 
- AF gave example of project he is currently working on which qualifies based on the building across the street (i.e. within a 1/4 mile radius) that has sufficiently high rent
- So say we screen 500 suitable properties, then for each we need to find a building within 1/4 mile that has market rental rates 40% above the threshold. Or say we find a 5 acre piece of raw land in downtown Detroit. If you have an apartment within 1/4 mile that is high rent and had sufficient rent diff (binary), then draw circle around this apt building, need to think through ... hurdle rate, representative property
- GT created trial accounts on [reonomy.com](reonomy.com) and [datafiniity.com](datafinity.com) and ran queries from the browser. Results shown in Slack. APIs are available for both: 
https://api.reonomy.com/v2/docs/api/data-dictionary/ 
https://developer.datafiniti.co/
- Both Reonomy and Datafinity allow searches by property type (e.g. Property Type: Multifamily (Reonomy), Apartment Building (Datafinity) but neither Reonomy nor Datafinity calls return rental values. Datafinity has a "Deposits" column which in most cases will equate to one month of rent, but it is sparsely populated so cannot be used as a rent proxy
- Identifying multi-family buildings and their corresponding rental estimates will require cross-referencing between data sources. For example, Realty Mole and Rentometer can return a rental estimate based on search criteria (e.g. lat/lng, address) but results will be for individual units and not an entire building while Reonomy and Datafinity can identify buildings. Same for raw land returned by a query, then we need to find an apartment within 1/4 mile that meets the high rent hurdle.
- Reiterated that we care about the rental estimates for use as a binary variable to determine whether affordability criterion is met. 
- **Data cleansing** will be a major task as ~100k properties have no lat/lng while some have incorrect lat/lng. AF will reload the Core Logic (CL) data to get more fields to help in data cleansing
- AF to pull Google transit data this week
- AF thinks it will be fairly easy to get _shape_ files from US Census Bureau which are polygons outlining legal boundaries of properties and will push Jupyter notebook to Github. This will facilitate data cleansing as we can check whether cross-referenced locations are contained in the polygons.
- AF: Still need to get a list of municipalities and census tracts with special status
- AF to get another shape file to identify criteria #6 (Development in Opportunity Zones and Rising Tide) which he believes are contained in Census Tracks which are a larger geography than Census Blocks 
- For criteria #5 (Affordable/Market Rent Differential), can also screen by Census Tract if shape file available, but may be trickier due to proximity of tracks (AF to update)
