### ISSUE TITLE
Team Call #5 - Dec 26 2020 @ 1830 EST

### ISSUE THREAD

**Issue by gpthio** [siads591-fa20-001-affordable-housing/go_blue#6]
**Summary**

- Reviewed AF-GT Zoom discussion yesterday regarding `PROPERTY INDICATOR` variable from CoreLogic and search radius for rental estimates returned by Rentometer API call
- Cannot find any APIs returning rental estimates that have search radius as a call parameter so will use the `radius_miles` parameter returned by Rentometer API and create binary flag for values < and >= 0.5 miles
- Going forward we will use King County data only to reduce data size and computational time
- Determined we can make free individual queries on [Google Places](https://cloud.google.com/maps-platform/pricing/sheet/?_ga=2.4099832.912090114.1609026144-1972218060.1606418159) up to 70,000 requests
- Next meeting set for Dec 29 @ 1830 EST

**Tasks**

- [ ] AF: Continue working on front-end data; upload King County subsetted data to Google Drive
- [ ] HKL: Continue managing DB; get up to speed on Plotly
- [ ] GT: Work through each `PROPERTY INDICATOR` code (total of 17) trying lat/lng coordinates of records to view actual properties on Google Maps and determine which codes represent types of multi-family housing; brush-up on Plotly
