### ISSUE TITLE
Team Call #6 - Dec 29 2020 @ 1845 EST

### ISSUE THREAD

**Issue by gpthio** [siads591-fa20-001-affordable-housing/go_blue#7]
**Summary**

- AF reviewed use of Google Places API to generate data for Grocery Stores which will be replicated for Schools, Senior Center, parks, Doctor's Office, Pharmacy
- API search parameters: JSON, user defined search terms (e.g. `groceries`, `grocery`, `supermarket`, `Michigan`),  input_type (`text_query`)  
- Next meeting @ Jan 2 1900 EST

**Tasks**

- [ ] AF: Upload CL data subsetted for KC and >=20 units including `PROPERTY INDICATOR` column and save as `gt20Units.csv`
- [ ] AF: Use Google API to append `type`, `address`, and `name` columns to append run `gt20Units.csv` 
- [ ] GT to do EDA on updated `gt20Units.csv` and check images as necessary to determine `PROPERTY INDICATOR` codes representing multi-family residential buildings
- [ ] KL: Continue to manage DB and installation of visualization packages 

**Notes**

_Google Places API_
- Input lat/lng into Google Places `location bias` field using 0.25 mi radius translated into lat/lng to find nearest grocery store with lat/lng for every 0.25 mile point 
- Return fields:  1. name  2. formatted address  3. geometry (lat/lng)  4. type (Google defined categorical variable - e.g. `Grocery`, `Supermarket`)  5. location_bias (max/min lat/lng for King County
- AF created empty df with two columns for lat and lng, populated df by calculating horiz and vert distance b/w coordinates, translating 0.25 mi to lat/lng. and running for loop to add return fields
- Subsetting CoreLogic (CL) data for King County (KC) reduces number of properties from 5m to 244k which will be subset further for min 20 units per property
- Expensive API call: User specifies categorical `type` parameter
- Cheap API call: User enters user-defined search string (e.g. as many relevant potential keywords/search terms) 
- Establishment types returned by Google are commercial only (e.g. `Restaurant`, `Grocery`) but can use this to eliminate non-residential properties in KC
- KC has 242k households vs 244k properties (all types) from CoreLogic which intuitively seems reasonable given multi-family buildings and non-residential buildings
