### ISSUE TITLE
Team Call #7 - Jan 2 2020 @ 1900 EST

### ISSUE THREAD

**Issue by gpthio** [siads591-fa20-001-affordable-housing/go_blue#8]
**Summary**
- CoreLogic (CL) data set reduced to 551 apartments in King County (KC)
- CL data has known discrepancies in number of units per apartment 
- Reviewed use and issues using KC shape files in [mapshaper](https://mapshaper.org/)
- Confirmed use of generic account for Postgres database (DB) to access data and run Jupyter notebook using Pandas [pd.read_sql](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_sql.html)
- Decided to drop use of crime data as information not granular enough
- Goal is to be able to produce average aggregate scores at the census block level which can be rolled up to block group and census tract level
- Confirmed final project submission date is Feb 3 @ 2359 EST

**Tasks**
- [ ] AF: Finish uploading data to Google Drive
- [ ] AF: Draw rough sketch of desired visualization
- [ ] HKL: Finish uploading data from Google Drive to Postgres database (DB)
- [ ] HKL: Provide code for reading data from DB
- [ ] GT: Convert KC geolocation data in ESRI shapefile to lat/lng for plotting and merging with CL lat/lng data
- [ ] GT: Debug plotting of KC data converted to geoJSON in Plotly
- [ ] GT: Check if number of units can be extracted from apartments.com [API](https://api.apartments.com/v1/) calls 
- [ ] GT: Try to extend Rentometer Pro Standard free trial account for 2 weeks (expired on Dec 31) or purchase
- [ ] GT/HKL: Share Google Maps APIs as AF near free usage limit
- [ ] GT/AF: If necessary, break up 551 KC apartment records and manually verify number of units on [apartments.com](url)
- [ ] GT/HKL/AF: Remember to document data sources on Google Drive 

**Notes**
- AF ran 9k CL records in [SmartyStreets](https://smartystreets.com/) to get 551 apartments in KC which passed manual spot check and included some seniors homes
- AF discovered incorrect unit counts for some known records so will try to use apartments.com API or worst case use apartments.com web interface to manually verify 
- HKL used mapshaper to convert KC shapefiles into geoJSON for Plotly (vs programmatic approach) but plots are not rendering
- KC geolocation data format needs to be converted to lat/lng for merging with CL data
- Crime data limited to only 8 cities/townships in KC vs total of ~30 so too broad to use as a search criteria
- AF has coded all properties by block so for example can return % of properties in a block within 1 mi of grocery store (binary variable) and show proximity of individual properties
- Census blocks will be color coded by average score and entire county will be displayed as a choropleth map
- HKL noted that Geopandas has a function to return distance, don’t necessarily have to rely on Google (just in case)
- Goal in Plotly is to draw outline of KC census blocks then be able to zoom-in to specific properties, let's do a sketch of the desired visualization
- ￼Allow user to select among 10 variables, show 2 at a time, 1 at block level, 1 at property, and also allow for filtering of variables (binary, categorical -- e.g. cost ranges)
- We will document and make available all the data sources and EDA, but just run Jupyter notebook starting with loading of aggregated KC apartment data from DB.
- If needed, there will be group office hours with the instructor
