### ISSUE TITLE
Team Call #8 - Jan 10 2021 @ 0900 EST #8

### ISSUE THREAD

**Issue by gpthio** [siads591-fa20-001-affordable-housing/go_blue#9]
**Summary**

- Minimum Viable Product (MVP) visualization functionality for scope review with faculty (date TBD):  Produce map with composite score at individual property level + ability to zoom in to see a color coded marker or property outline.
- MVP+ features: Ability to zoom out to see higher level composite scoring  (e.g. Block, Block Group (BG)) + explore individual scoring components (e.g. Amenities)
- Plotly: Reviewed progress and worked on some troubleshooting including handling of shape files and translating CRS code to lat/lng
- Propose next Zoom meeting on Feb 16 @ 0900 EST

**Tasks**

- [ ] HKL: Define a DB view to join all tables 
- [ ] HKL: Prepare a product specification sheet to surface any missing info or items for further clarification
- [ ] ALL: Decide on meeting with Chris and Anthony after our next Zoom
- [ ] HKL: Enjoy time with daughter before she flies off for Ann Arbor!
- [ ] AF/GT: Prepare for exam!

**Notes**

Geodata
- Discussed defining a view in DB to join tables, `pd.read_sql` will automatically set data types
- AF to upload one more file (Walk Score) which is categorical (0, 5, 7,  12), could be transformed into separate columns
- Should be able to associate tax files 1-to-1 with KC shape files (note: files have 250k rows)
- [EPSG library for Michigan South](https://epsg.org/crs_2253/NAD83-Michigan-South-ft.html?sessionkey=kqx6pnul0b)
- 2253 is the international CRS code for Michigan
- EPSG library will be used by Plotly to do the projection so somewhere in here need to put in the CRS code
- Using geoPandas, can add this code (it is a characteristic of the geometry in geoPandas) and can translate from CRS projection code to lat/lng
- Reference: [GeoPandas Managing Projections - Coordinate Reference Systems](https://geopandas.org/projections.html#:~:text=What%20is%20the%20best%20format,potentially%20leading%20to%20erroneous%20transformations.
- _The same CRS can often be referred to in many ways. For example, one of the most commonly used CRS is the WGS84 latitude-longitude projection. This can be referred to using the authority code "EPSG:4326"._
- If dataset is imported into geoPandas, have to first define geometry before conversion so it knows basis of conversion (i.e. baseline vs target)
- Southern MI uses feet instead of metres! .... crash landing on international Mars mission was due to US scientists using Imperial vs EU scientists using metric :-0 ... and there is such a thing as `international feet` as used in Southern MI (miniscule difference vs standard feet to facilitate better conversion to metric)

_UX for Visualization_
- Overarching guideline: What is essential for the target user (property developer)? Don't want utility to be compromised by complexity. 
- Can plot block groups based on continuous spectrum or cutoff of composite score, then zoom in to each block to see individual properties which will render as score (e.g. color encoded)
- Desired Information-Source for hover/tooltips: 
1. Name of Owner - CL
2. Sev - CL
3. Size (Acreage or Shape Area) - CL(?) or functions to calculate area
4. Address  - Google reverse geocoding 
- Can plot BG as a layer (at high individual properties are too small to see) 
- From a BG perspective can see percentage that meet threshold rating, then zoom in to see individual properties
- From structured data point of view, BG is an aggregation of groups 
- One approach is to score all properties based on a composite formula. User can specify a cutoff (e.g. using a continuous slider) which will then display the percentage of properties in each block that achieve this score coded by color
- Need to resist allowing ability to view too many attributes as it can easily confuse the user
- Need to decide level of interactivity and how it is actioned (e.g. dropdowns, sliders, check boxes). May even want the user to be able to change the composite scoring weights if they want to explore a particular feature rather than just the composite score
- Attributes could be grouped with check boxes such as Amenities (itself could be grouped) and Walk Score
- Screen shared Parcel Mapper in Grand Rapids to iterate viz ideas 
- Believe we can overlay overlay satellite photographs in Plotly but level of detail still TBD 
- So say user starts at KC view, sees BGs color coded according to something, then let user checkbox amenities ￼
- Looked at quarter township (QT) sections on Parcel Mapper which are analogous to BG for our discussion: QT <-> PM
- Want data at 2 levels: QT, individual property. At QT level, we encoding composite score of each of quarter by color and keep that background color as we zoom in ... 
- Need to stay focused on the property first as this is the basic building block (no pun intended) then we can move up to higher levels
- OK we have formula for property composite score then we zoom up ... What do we see? See outline of section. What else? Colored if a parameter was selected and color is according to % meeting criteria (binary or categorical) but can only look at one feature at a time. So you would have one slider which will slide based on the box-ticked parameter. For example, if slider range is is 0-4 and you move it to 3, then view is color coded by % of homes that have 3 (or maybe >=3).
- Agreed that amenities should be grouped with no option to view individual parameters

_Practioner Workflow (AF)_
- Start high level (QT), see overall score of QT, then choose a QT (e.g. E Grand Rapids). Start to see plots, see color codings of individual properties, then look to see if there are any large properties. Click on a property, maybe score is too low, so start looking around the quarter to see see individual scores.  Maybe transportation score is low so you zoom out and decide this is not the best area￼
- MSHDA scoring is 0-180 and it is 100% quantitative (composition of score does not matter)
￼- Good information on the Parcel Mapper hover/tooltip: Try to download as much of this data as possible
- Overlay of the actual map would be nice but not MVP. Need to check if KC provides a mapping overlay but put aside for now
- Will be interesting to see top areas in KC, have no preconceived notions!

**Comment by hokoonleong** [comment]
Hi George - Thanks.  Only one comment, Feb 16 is a bit late for the next meeting the course would be over by then...

Go Blue!
Koon Leong
